#!/bin/bash

# SentinelFS - Unified Launch Script
# This script builds and launches SentinelFS with all paths correctly configured

set -e  # Exit on error

# Ensure we are in the project root
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║      SentinelFS Launch Script          ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"

# === Configuration ===
BUILD_DIR="$PROJECT_ROOT/build"
PLUGIN_DIR="$BUILD_DIR/plugins"
LIB_DIR="$BUILD_DIR/core"
DAEMON_BIN="$BUILD_DIR/app/daemon/sentinel_daemon"
SYNC_DIR="$HOME/SentinelFS"
CONFIG_DIR="$HOME/.config/sentinelfs"
CONFIG_FILE="$CONFIG_DIR/sentinel.conf"

# === Functions ===
check_dependencies() {
    echo -e "${BLUE}[1/5] Checking dependencies...${NC}"
    local missing=()
    
    command -v cmake >/dev/null 2>&1 || missing+=("cmake")
    command -v make >/dev/null 2>&1 || missing+=("make")
    command -v node >/dev/null 2>&1 || missing+=("nodejs")
    command -v npm >/dev/null 2>&1 || missing+=("npm")
    
    if [ ${#missing[@]} -ne 0 ]; then
        echo -e "${RED}Missing dependencies: ${missing[*]}${NC}"
        echo -e "${YELLOW}Install them with: sudo apt install ${missing[*]}${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ All dependencies found${NC}"
}

setup_directories() {
    echo -e "${BLUE}[2/5] Setting up directories...${NC}"
    
    # Create sync directory
    if [ ! -d "$SYNC_DIR" ]; then
        mkdir -p "$SYNC_DIR"
        echo -e "${GREEN}✓ Created sync directory: $SYNC_DIR${NC}"
    fi
    
    # Create config directory
    mkdir -p "$CONFIG_DIR"
    
    # Create or update config file with correct defaults
    if [ ! -f "$CONFIG_FILE" ]; then
        cat > "$CONFIG_FILE" << EOF
# SentinelFS Configuration
# Generated by start_safe.sh on $(date)

# Network Settings
tcp_port=8080
discovery_port=9999
metrics_port=9100

# Sync Settings
watch_directory=$SYNC_DIR
encryption_enabled=false

# Bandwidth Limits (0 = unlimited, in KB/s)
upload_limit_kbps=0
download_limit_kbps=0

# Security (uncomment and set to enable)
# session_code=XXXXXX
EOF
        echo -e "${GREEN}✓ Created config file: $CONFIG_FILE${NC}"
    else
        # Update watch_directory if it's set to old value
        if grep -q "watch_directory=~/sentinel_sync" "$CONFIG_FILE" 2>/dev/null; then
            sed -i "s|watch_directory=~/sentinel_sync|watch_directory=$SYNC_DIR|g" "$CONFIG_FILE"
            echo -e "${YELLOW}✓ Updated watch_directory in config${NC}"
        fi
    fi
    
    echo -e "${GREEN}✓ Directories configured${NC}"
}

build_daemon() {
    echo -e "${BLUE}[3/5] Building daemon...${NC}"
    
    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"
    
    # Configure with CMake
    if [ ! -f "Makefile" ] || [ "$1" == "--rebuild" ]; then
        echo -e "${YELLOW}Running CMake...${NC}"
        cmake .. -DCMAKE_BUILD_TYPE=Debug
    fi
    
    # Build
    make -j$(nproc) 2>&1 | tail -20
    
    if [ ! -f "$DAEMON_BIN" ]; then
        echo -e "${RED}✗ Daemon build failed!${NC}"
        exit 1
    fi
    
    # Verify plugins are built
    local plugins_ok=true
    # Check new plugin structure: netfalcon, ironroot, storage, zer0
    declare -A plugin_libs=(
        ["storage"]="storage/libstorage_plugin.so"
        ["netfalcon"]="netfalcon/libnetfalcon.so"
        ["ironroot"]="ironroot/libironroot.so"
        ["zer0"]="zer0/libzer0.so"
    )
    for plugin in "${!plugin_libs[@]}"; do
        if [ ! -f "$PLUGIN_DIR/${plugin_libs[$plugin]}" ]; then
            echo -e "${RED}✗ Missing plugin: $plugin${NC}"
            plugins_ok=false
        fi
    done
    
    if [ "$plugins_ok" = false ]; then
        echo -e "${RED}Plugin build incomplete!${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ Daemon and plugins built successfully${NC}"
    cd "$PROJECT_ROOT"
}

setup_gui() {
    echo -e "${BLUE}[4/5] Setting up GUI...${NC}"
    
    cd "$PROJECT_ROOT/gui"
    
    if [ ! -d "node_modules" ]; then
        echo -e "${YELLOW}Installing npm dependencies...${NC}"
        npm install --silent
    fi
    
    echo -e "${GREEN}✓ GUI ready${NC}"
    cd "$PROJECT_ROOT"
}

launch_app() {
    echo -e "${BLUE}[5/5] Launching SentinelFS...${NC}"
    
    # Export environment variables for daemon
    export SENTINELFS_PLUGIN_DIR="$PLUGIN_DIR"
    export LD_LIBRARY_PATH="$LIB_DIR:${LD_LIBRARY_PATH:-}"
    export GDK_BACKEND=x11
    
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║         Configuration Summary          ║${NC}"
    echo -e "${GREEN}╠════════════════════════════════════════╣${NC}"
    echo -e "${GREEN}║${NC} Sync Directory: ${BLUE}$SYNC_DIR${NC}"
    echo -e "${GREEN}║${NC} Config File:    ${BLUE}$CONFIG_FILE${NC}"
    echo -e "${GREEN}║${NC} Plugin Dir:     ${BLUE}$PLUGIN_DIR${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
    echo ""
    
    cd "$PROJECT_ROOT/gui"
    
    # Launch with filtered output (suppress GTK warnings)
    npm run dev 2>&1 | grep -v "GLib-GObject\|GtkFileChooserNative\|gsignal.c\|Gtk-WARNING"
}

# === CLI Options ===
show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --daemon-only    Only start the daemon (no GUI)"
    echo "  --rebuild        Force rebuild from scratch"
    echo "  --help           Show this help message"
    echo ""
}

start_daemon_only() {
    echo -e "${BLUE}Starting daemon only...${NC}"
    
    export SENTINELFS_PLUGIN_DIR="$PLUGIN_DIR"
    export LD_LIBRARY_PATH="$LIB_DIR:${LD_LIBRARY_PATH:-}"
    
    echo -e "${GREEN}Environment configured:${NC}"
    echo "  SENTINELFS_PLUGIN_DIR=$SENTINELFS_PLUGIN_DIR"
    echo "  LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
    echo ""
    
    exec "$DAEMON_BIN" "$@"
}

# === Main ===
case "${1:-}" in
    --help|-h)
        show_help
        exit 0
        ;;
    --daemon-only)
        shift
        check_dependencies
        setup_directories
        build_daemon
        start_daemon_only "$@"
        ;;
    --rebuild)
        check_dependencies
        setup_directories
        rm -rf "$BUILD_DIR"
        build_daemon --rebuild
        setup_gui
        launch_app
        ;;
    *)
        check_dependencies
        setup_directories
        build_daemon
        setup_gui
        launch_app
        ;;
esac

